// Canonical site config for SEO.
//
// PRODUCTION_URL is the one domain every canonical tag, Open Graph URL and
// sitemap entry must point at. It is deliberately hard-coded: a Semrush audit
// (2026-08-01) found the whole site canonicalising to the Vercel preview host,
// which tells Google the real content lives there and leaves the real domain
// unranked. NEXT_PUBLIC_SITE_URL can still override it for local work, but a
// *.vercel.app value is ignored so a stale deploy env var can never bring the
// bug back.
const PRODUCTION_URL = "https://www.thereisanaiforyou.com";

function resolveSiteUrl(): string {
  const raw = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (!raw) return PRODUCTION_URL;
  const url = raw.replace(/\/$/, "");
  // Preview/deploy hosts must never become the canonical domain.
  if (/^https?:\/\/[^/]*\.vercel\.app$/i.test(url)) return PRODUCTION_URL;
  return url;
}

export const SITE_URL = resolveSiteUrl();

export const SITE_NAME = "TAIFY";
export const SITE_TAGLINE = "There's An AI For You";
export const SITE_DESCRIPTION =
  "The field guide to AI tools. Describe your task, get the right tool - verified daily, honest pricing.";

/** Site-wide social preview image (generated by app/opengraph-image.tsx). */
export const OG_IMAGE = `${SITE_URL}/opengraph-image`;

/**
 * The site-wide social card in the shape `Metadata["openGraph"]["images"]`
 * wants.
 *
 * Next replaces the layout's `openGraph` / `twitter` objects wholesale when a
 * page declares its own — it does not merge them key by key — so every page
 * that sets an OG title also drops the layout's image unless it passes one back
 * in. That is how the category pages, /browse, /categories and the role pages
 * ended up shipping no `og:image` at all while the homepage had one.
 */
export const OG_IMAGE_CARD = [
  { url: OG_IMAGE, width: 1200, height: 630, alt: `${SITE_NAME} - ${SITE_TAGLINE}` },
];

export function absoluteUrl(path: string): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

/**
 * Longest title-tag length we allow. Semrush flags anything over 70 characters
 * and Google truncates the SERP display around 60, so titles are built to fit
 * 60 where possible and are never allowed past 70.
 */
export const TITLE_TARGET = 60;
export const TITLE_MAX = 70;

const BRAND_SUFFIX = ` · ${SITE_NAME}`;

/**
 * Append the brand to a title, shortening the title itself when the suffix
 * would otherwise not fit inside `max`.
 *
 * This is the fix for Semrush's "duplicate content in h1 and title" warning:
 * pages whose H1 is the raw title get a distinct, brand-suffixed <title>. The
 * suffix is the *only* thing making the two differ, so it must never be
 * dropped — the previous all-or-nothing version returned the bare title once a
 * headline passed `max - 8` (62) characters, which is exactly how two posts
 * with 63- and 67-character headlines ended up with a <title> that matched
 * their H1 character for character.
 *
 * Truncation is at a word boundary and only when the cut would split a word,
 * so a headline that ends flush against the limit keeps its last word.
 */
export function withBrand(title: string, max = TITLE_MAX): string {
  const t = title.trim();
  if (t.endsWith(BRAND_SUFFIX) || t.endsWith(`| ${SITE_NAME}`)) return t;
  const room = max - BRAND_SUFFIX.length;
  // Nothing sensible to append into: hand back a title that at least fits.
  if (room < 20) return t.slice(0, max);
  if (t.length <= room) return t + BRAND_SUFFIX;
  const cut = t.slice(0, room);
  // Only back off to the previous space when `room` lands mid-word.
  const space = cut.lastIndexOf(" ");
  const base = t[room] === " " || space <= 20 ? cut : cut.slice(0, space);
  return base.replace(/[\s·|,:;?!-]+$/, "") + BRAND_SUFFIX;
}

/**
 * Pick the first candidate title that fits `max`, falling back to the last one
 * trimmed at a word boundary. Used to keep generated titles inside the limit
 * without ever emitting a mid-word cut.
 */
export function pickTitle(candidates: string[], max = TITLE_TARGET): string {
  for (const c of candidates) {
    const t = c.trim();
    if (t && t.length <= max) return t;
  }
  const last = (candidates[candidates.length - 1] ?? "").trim();
  if (last.length <= max) return last;
  const cut = last.slice(0, max);
  const space = cut.lastIndexOf(" ");
  return (space > 20 ? cut.slice(0, space) : cut).replace(/[\s·\-|,:]+$/, "");
}

/**
 * Words that cannot be the last word of a sentence.
 *
 * Clipping at a word boundary lands on one of these constantly, because they
 * are exactly the words that introduce the clause being cut off: the audit
 * found 73 of 218 tool pages ending "…with a capable free tier and",
 * "…answers questions across your", "…and validate emerging trends -". They
 * are dropped from the tail until the description ends on a word that can carry
 * a full stop.
 */
const DANGLING = new Set(
  `a an the this that these those its their your our his her my no any some each every
   both either neither another other such same
   and or but nor so yet plus versus vs
   of in on at to for with from by into onto over under above below across through
   throughout between among amongst against about than per via without within upon
   toward towards during before after since until till unless while whilst despite
   besides beyond beneath behind along around near off out up down like as including
   which who whom whose whether when where how why what
   is are was were be been being am has have had do does did
   can could will would shall should may might must
   rather instead not more most less least also even still just only very well`.split(/\s+/),
);

/** Trailing punctuation left behind once the clause after it has been cut. */
const TRAILING_PUNCT = /[\s,;:/&+·\-–—]+$/u;

/**
 * Hard ceiling for a meta description. Semrush warns past 160 characters and
 * Google's snippet runs out around the same point, so `max` is the target and
 * this is the point where a description has to be shortened rather than shipped
 * whole.
 */
const DESCRIPTION_MAX = 160;

/**
 * Shortest description worth shipping. Below this a clause boundary is throwing
 * away more than it saves, and a word-level cut is the better trade.
 */
const DESCRIPTION_MIN = 70;

/**
 * How much text a clause boundary has to add past the last full stop before it
 * beats ending on that full stop. Under it the boundary is a few words into a
 * second sentence and leaves a stub — "…as an interactive app. Its notebook."
 */
const MIN_TAIL = 25;

/**
 * Build a meta description from arbitrary text (HTML allowed), ending it on a
 * complete sentence or clause inside `max`. Used as the fallback when a post,
 * tool or page has no hand-written excerpt, so no page ships without one.
 *
 * The old version clipped at the last space and appended an ellipsis, which put
 * 73 of the 218 tool pages into the SERP mid-clause — "…with a capable free
 * tier and", "…answers questions across your", "…deployed in 1,600". That last
 * one is the reason this backs off to a clause boundary instead of trimming
 * hanging words one at a time: a word-level cut can land inside a figure and
 * change what the sentence claims.
 */
export function metaDescription(source: string, max = 155): string {
  const text = source
    .replace(/<[^>]+>/g, " ")
    .replace(/&(nbsp|amp|lt|gt|quot|#39);/g, (_m, e) =>
      ({ nbsp: " ", amp: "&", lt: "<", gt: ">", quot: '"', "#39": "'" })[e as string] ?? " ",
    )
    .replace(/\s+/g, " ")
    .trim();
  if (!text) return "";
  if (text.length <= max) return text;
  // A description a few characters over target reads better whole than reeled
  // back to its previous clause, and still fits the snippet.
  if (text.length <= Math.min(Math.max(max + 5, max), DESCRIPTION_MAX)) return text;

  // Walk for the last sentence or clause boundary that fits. The latest one
  // wins because it carries the most of the original: a sentence end keeps its
  // full stop, a comma / semicolon / dash trades its punctuation for one. The
  // lookahead reads past `max`, so a boundary sitting exactly on the limit
  // still counts rather than being missed by one character.
  let end = -1;
  let complete = false;
  let lastSentence = -1;
  const limit = Math.min(max, text.length - 2);
  for (let i = 1; i <= limit; i += 1) {
    if (text[i + 1] !== " ") continue;
    const c = text[i];
    if (c === "." || c === "!" || c === "?") {
      end = i + 1;
      complete = true;
      lastSentence = end;
    } else if (c === "," || c === ";" || c === ":") {
      end = i;
      complete = false;
    } else if ((c === "-" || c === "–" || c === "—") && text[i - 1] === " ") {
      end = i - 1;
      complete = false;
    }
  }

  // Prefer the full stop when the clause boundary is only a few words past it.
  if (!complete && lastSentence > 0 && end - lastSentence < MIN_TAIL) {
    end = lastSentence;
    complete = true;
  }

  if (end >= Math.min(DESCRIPTION_MIN, max * 0.5)) {
    return complete ? text.slice(0, end) : `${text.slice(0, end).replace(TRAILING_PUNCT, "")}.`;
  }

  // No usable boundary: fall through to a word cut with the hanging words
  // reeled off instead.

  let out = text.slice(0, max);
  const space = out.lastIndexOf(" ");
  if (space > 0) out = out.slice(0, space);
  for (;;) {
    const before = out;
    out = out.replace(TRAILING_PUNCT, "");
    const last = /(?:^|\s)([A-Za-z][A-Za-z'’]*)$/.exec(out);
    if (last && DANGLING.has(last[1].toLowerCase())) out = out.slice(0, last.index);
    if (out === before) break;
  }
  out = out.trim();
  if (!out) return "";
  return /[.!?]$/.test(out) ? out : `${out}.`;
}
