// Canonical site config for SEO.
//
// PRODUCTION_URL is the one domain every canonical tag, Open Graph URL and
// sitemap entry must point at. It is deliberately hard-coded: a Semrush audit
// (2026-08-01) found the whole site canonicalising to the Vercel preview host,
// which tells Google the real content lives there and leaves the real domain
// unranked. NEXT_PUBLIC_SITE_URL can still override it for local work, but a
// *.vercel.app value is ignored so a stale deploy env var can never bring the
// bug back.
const PRODUCTION_URL = "https://www.thereisanaiforyou.com";

function resolveSiteUrl(): string {
  const raw = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (!raw) return PRODUCTION_URL;
  const url = raw.replace(/\/$/, "");
  // Preview/deploy hosts must never become the canonical domain.
  if (/^https?:\/\/[^/]*\.vercel\.app$/i.test(url)) return PRODUCTION_URL;
  return url;
}

export const SITE_URL = resolveSiteUrl();

export const SITE_NAME = "TAIFY";
export const SITE_TAGLINE = "There's An AI For You";
export const SITE_DESCRIPTION =
  "The field guide to AI tools. Describe your task, get the right tool - verified daily, honest pricing.";

/** Site-wide social preview image (generated by app/opengraph-image.tsx). */
export const OG_IMAGE = `${SITE_URL}/opengraph-image`;

export function absoluteUrl(path: string): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

/**
 * Longest title-tag length we allow. Semrush flags anything over 70 characters
 * and Google truncates the SERP display around 60, so titles are built to fit
 * 60 where possible and are never allowed past 70.
 */
export const TITLE_TARGET = 60;
export const TITLE_MAX = 70;

const BRAND_SUFFIX = ` · ${SITE_NAME}`;

/**
 * Append the brand to a title, shortening the title itself when the suffix
 * would otherwise not fit inside `max`.
 *
 * This is the fix for Semrush's "duplicate content in h1 and title" warning:
 * pages whose H1 is the raw title get a distinct, brand-suffixed <title>. The
 * suffix is the *only* thing making the two differ, so it must never be
 * dropped — the previous all-or-nothing version returned the bare title once a
 * headline passed `max - 8` (62) characters, which is exactly how two posts
 * with 63- and 67-character headlines ended up with a <title> that matched
 * their H1 character for character.
 *
 * Truncation is at a word boundary and only when the cut would split a word,
 * so a headline that ends flush against the limit keeps its last word.
 */
export function withBrand(title: string, max = TITLE_MAX): string {
  const t = title.trim();
  if (t.endsWith(BRAND_SUFFIX) || t.endsWith(`| ${SITE_NAME}`)) return t;
  const room = max - BRAND_SUFFIX.length;
  // Nothing sensible to append into: hand back a title that at least fits.
  if (room < 20) return t.slice(0, max);
  if (t.length <= room) return t + BRAND_SUFFIX;
  const cut = t.slice(0, room);
  // Only back off to the previous space when `room` lands mid-word.
  const space = cut.lastIndexOf(" ");
  const base = t[room] === " " || space <= 20 ? cut : cut.slice(0, space);
  return base.replace(/[\s·|,:;?!-]+$/, "") + BRAND_SUFFIX;
}

/**
 * Pick the first candidate title that fits `max`, falling back to the last one
 * trimmed at a word boundary. Used to keep generated titles inside the limit
 * without ever emitting a mid-word cut.
 */
export function pickTitle(candidates: string[], max = TITLE_TARGET): string {
  for (const c of candidates) {
    const t = c.trim();
    if (t && t.length <= max) return t;
  }
  const last = (candidates[candidates.length - 1] ?? "").trim();
  if (last.length <= max) return last;
  const cut = last.slice(0, max);
  const space = cut.lastIndexOf(" ");
  return (space > 20 ? cut.slice(0, space) : cut).replace(/[\s·\-|,:]+$/, "");
}

/**
 * Build a meta description from arbitrary text (HTML allowed), clamped to a
 * sentence or word boundary inside `max`. Used as the fallback when a post or
 * page has no hand-written excerpt, so no page ships without a description.
 */
export function metaDescription(source: string, max = 155): string {
  const text = source
    .replace(/<[^>]+>/g, " ")
    .replace(/&(nbsp|amp|lt|gt|quot|#39);/g, (_m, e) =>
      ({ nbsp: " ", amp: "&", lt: "<", gt: ">", quot: '"', "#39": "'" })[e as string] ?? " ",
    )
    .replace(/\s+/g, " ")
    .trim();
  if (!text) return "";
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  const sentence = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf("! "), cut.lastIndexOf("? "));
  if (sentence > max * 0.6) return cut.slice(0, sentence + 1);
  const space = cut.lastIndexOf(" ");
  return `${(space > 0 ? cut.slice(0, space) : cut).replace(/[\s,;:]+$/, "")}…`;
}
