// Capture a homepage screenshot for every tool and write a SCREENSHOTS map.
// Usage: npx tsx scripts/shoot.mts   (optionally pass slugs to (re)capture a subset)
import { chromium } from "playwright";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { TOOLS } from "../src/data/tools";

const OUT_DIR = path.join(process.cwd(), "public", "shots");
const only = new Set(process.argv.slice(2));
const targets = TOOLS.filter((t) => only.size === 0 || only.has(t.slug));

await mkdir(OUT_DIR, { recursive: true });

const browser = await chromium.launch();
const ctx = await browser.newContext({
  viewport: { width: 1280, height: 800 },
  userAgent:
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36",
  deviceScaleFactor: 1,
});

const ok: Record<string, string> = {};
const failed: string[] = [];

for (const t of targets) {
  const page = await ctx.newPage();
  try {
    await page.goto(t.url, { waitUntil: "domcontentloaded", timeout: 25000 });
    // Let hero content / fonts settle, and dismiss obvious cookie banners.
    await page.waitForTimeout(2500);
    for (const label of ["Accept", "Accept all", "I agree", "Got it", "Allow all"]) {
      const btn = page.getByRole("button", { name: label, exact: false }).first();
      if (await btn.isVisible().catch(() => false)) {
        await btn.click().catch(() => {});
        await page.waitForTimeout(400);
        break;
      }
    }
    const buf = await page.screenshot({ type: "jpeg", quality: 78 });
    await writeFile(path.join(OUT_DIR, `${t.slug}.jpg`), buf);
    ok[t.slug] = `/shots/${t.slug}.jpg`;
    console.log(`  ok   ${t.slug}`);
  } catch (e) {
    failed.push(t.slug);
    console.log(`  FAIL ${t.slug}  (${String((e as Error).message).slice(0, 60)})`);
  } finally {
    await page.close();
  }
}

await browser.close();

// Merge with any previously captured shots so a partial re-run never drops entries.
let prev: Record<string, string> = {};
try {
  prev = (await import("../src/data/screenshots")).SCREENSHOTS;
} catch {
  /* first run - no file yet */
}
const merged = { ...prev, ...ok };
const body =
  "// Auto-generated by scripts/shoot.mts - homepage screenshots per tool slug.\n" +
  "export const SCREENSHOTS: Record<string, string> = " +
  JSON.stringify(merged, null, 2) +
  ";\n";
await writeFile(path.join(process.cwd(), "src", "data", "screenshots.ts"), body);

console.log(`\ncaptured ${Object.keys(ok).length}/${targets.length}, total ${Object.keys(merged).length}`);
if (failed.length) console.log(`failed: ${failed.join(", ")}`);
